### ISSUE TITLE
can't open http://localhost:8818

### ISSUE THREAD

**Issue by nuonuoxiangyaofeigaogao** [smalltong02/keras-llm-robot#32]
Hello, I have great interest in your project! I have finished all of your 'Environment Setup' successfully, Then enter 'python __webgui_server__.py --webui' in Linux, I got below,
![1712718659855](https://github.com/smalltong02/keras-llm-robot/assets/94776588/29f532a3-bb99-4f0b-98a4-7f9036c5fd53)

However, when I want to open this page number with xxx.xxx.xxx.xxx:8818 in my Local browser, I got nothing, just like below,
![image](https://github.com/smalltong02/keras-llm-robot/assets/94776588/39532db3-ef26-41c1-9674-ba9e0599fe04)

Then I find I can open xxx.xxx.xxx.xxx:8819 with a error tips.
![image](https://github.com/smalltong02/keras-llm-robot/assets/94776588/2803f3ff-23ac-43bd-aff0-539cfcfef6c9)

I don't know why these essues occurred. Could you help me? Thanks a lot!

**Comment by smalltong02** [comment]
Hello, The main program for viewing the image has been loaded successfully, If you are not using a reverse proxy and are opening the webUI on local PC, please use http://localhost:8818 or http://127.0.0.1:8818, Please do not use http://(ip-address):8818

If you want to access the webUI on other PC within the same local network, please use the following command to running reverse proxy:
      chmod +x ./tools/ssl-proxy-linux
      ./tools/ssl-proxy-linux -from 0.0.0.0:4480 -to 127.0.0.1:8818
you can use https://(ip-address):8818 to access the webUI.

for the 8819 issue, This is a known issue, and I will fix it in the future.

Thank you very much for using and providing feedback!

**Comment by nuonuoxiangyaofeigaogao** [comment]
Sorry for lost your reply in time! I have try the solution you given, 
![image](https://github.com/smalltong02/keras-llm-robot/assets/94776588/34ea9a4d-daa0-4964-87a1-8d3768bde0c1)
however, I still can't access the webUI from another PC with https://(ip-address):8818.
![image](https://github.com/smalltong02/keras-llm-robot/assets/94776588/1bb3f63a-aaa3-4f4e-8a5e-92ba523f864d)
It's really strange
![image](https://github.com/smalltong02/keras-llm-robot/assets/94776588/edf73d49-bc57-4697-b539-d7fc922717c6)

**Comment by smalltong02** [comment]
Port 8818 is mapped to port 4480, so please visit https://192.168.1.19:4480 on another PC.

**Comment by nuonuoxiangyaofeigaogao** [comment]
> Port 8818 is mapped to port 4480, so please visit https://192.168.1.19:4480 on another PC.

That's good!!! I have access https://192.168.1.19:4480/!!Thanks for your kindly help!!!
